name: Mythic+ Tracker

on:
  schedule:
    - cron: '0 13 * * 1'  # Every Monday at 9AM Eastern (13:00 UTC)
  workflow_dispatch:

jobs:
  run-tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread oauth2client requests

      - name: Run mythic tracker
        env:
          GOOGLE_CREDS_JSON: ${{ secrets.GOOGLE_CREDS_JSON }}
          GOOGLE_SHEET_KEY: ${{ secrets.GOOGLE_SHEET_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_ROLE_ID: ${{ secrets.DISCORD_ROLE_ID }}
        run: |
          echo "$GOOGLE_CREDS_JSON" > creds.json
          python mythic_tracker.py
